//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вакансия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вакансия()
        {
            this.Отклик = new HashSet<Отклик>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодСпециальности { get; set; }
        public Nullable<int> КодРаботодателя { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<bool> Статус { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Опыт { get; set; }
        public string Зарплата { get; set; }
    
        public virtual Работодатель Работодатель { get; set; }
        public virtual Специальности Специальности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отклик> Отклик { get; set; }
    }
}
