//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отклик
    {
        public int Код { get; set; }
        public int КодВакансии { get; set; }
        public int КодПользователя { get; set; }
        public System.DateTime ДатаОтправки { get; set; }
        public int Статус { get; set; }
    
        public virtual Вакансия Вакансия { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
