//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Специалист
    {
        public int Код { get; set; }
        public string Фио { get; set; }
        public string Телефон { get; set; }
        public string Пароль { get; set; }
    }
}
